import keyMirror from 'key-mirror';

export default keyMirror({
  SET_PLATFORM:null,
  SET_VERSION:null,

  SESSION_TOKEN_REQUEST:null,
  SESSION_TOKEN_SUCCESS:null,
  SESSION_TOKEN_FAILURE:null,

  DELETE_TOKEN_REQUEST:null,
  DELETE_TOKEN_SUCCESS:null,

  ON_LOGIN_STATE_CHANGE:null,
  LOGOUT:null,

  ON_AUTH_FORM_FIELD_CHANGE:null,
  SIGNUP_REQUEST:null,
  SIGNUP_SUCCESS:null,
  SIGNUP_FAILURE:null,

  LOGIN_REQUEST:null,
  LOGIN_SUCCESS:null,
  LOGIN_FAILURE:null,

  LOGOUT_REQUEST:null,
  LOGOUT_SUCCESS:null,
  LOGOUT_FAILURE:null,

  LOGGED_IN:null,
  LOGGED_OUT:null,

  SET_SESSION_TOKEN:null,

  RESET_PASSWORD_REQUEST:null,
  RESET_PASSWORD_SUCCESS:null,
  RESET_PASSWORD_FAILURE:null,

  GET_PROFILE_REQUEST:null,
  GET_PROFILE_SUCCESS:null,
  GET_PROFILE_FAILURE:null,

  ON_PROFILE_FORM_FIELD_CHANGE:null,

  PROFILE_UPDATE_REQUEST:null,
  PROFILE_UPDATE_SUCCESS:null,
  PROFILE_UPDATE_FAILURE:null,

  SET_STATE:null,
  GET_STATE:null,
  SET_STORE:null,

  FORGOT_PASSWORD:null,
  LOGIN:null,
  REGISTER:null,



  /* START 新闻模块 */
  // 获取指定新闻
  GET_NEWS_REQUEST:null,
  GET_NEWS_SUCCESS:null,
  GET_NEWS_FAILURE:null,
  // 列出新闻列表
  LIST_NEWS_REQUEST:null,
  LIST_NEWS_SUCCESS:null,
  LIST_NEWS_FAILURE:null,
  // 点赞
  GOOD_NEWS_REQUEST:null,
  GOOD_NEWS_SUCCESS:null,
  GOOD_NEWS_FAILURE:null,
  // 差评
  BAD_NEWS_REQUEST:null,
  BAD_NEWS_SUCCESS:null,
  BAD_NEWS_FAILURE:null,
  // 评论
  COMMENT_NEWS_REQUEST:null,
  COMMENT_NEWS_SUCCESS:null,
  COMMENT_NEWS_FAILURE:null,
  // 列出新闻评论
  LIST_NEWS_COMMENTS_REQUEST:null,
  LIST_NEWS_COMMENTS_SUCCESS:null,
  LIST_NEWS_COMMENTS_FAILURE:null,
  // 列出指定新闻子评论
  LIST_NEWS_COMMENTS_SUB_REQUEST:null,
  LIST_NEWS_COMMENTS_SUB_SUCCESS:null,
  LIST_NEWS_COMMENTS_SUB_FAILURE:null,
  /* END 新闻模块 */

});
